plugins {
    id 'com.android.application'
}

android {
    namespace 'win.fantest.touchguard'
    compileSdk 35

    defaultConfig {
        applicationId "win.fantest.touchguard"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
